# Generated by Django 5.0.6 on 2024-05-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estado_id',
        ),
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tareas', to='planner.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tareas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='planner.tarea'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
